# Generated by Django 5.1.6 on 2025-02-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_unique_email_supplier_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
    ]
